## datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-transactions
    username: postgres
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  # SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs
# LOGGING
logging:
  level:
    org.springframework:
      transaction: TRACE
      orm:
        jpa: TRACE
      jdbc: TRACE

