## default connection pool
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-transactions
    username: postgres
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect

  # SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs
  
  # postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
  
  # schema name in postgreSQL -> 'boot_postgres'
spring.jpa.properties.hibernate.default_schema=bootPostgres
